# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
